name: venomous_app_chat
description: "blaxberry333's venomous apps chat"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dots_indicator: ^3.0.0
  logger: ^2.5.0
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/uploads/

  fonts:
    - family: Anton
      fonts:
        - asset: fonts/anton.ttf
